services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        build:
            context: ./producer/image-def
        volumes:
            - ./producer/app:/source
    consumer-a:
        build:
            context: ./consumer-a/image-def
        volumes:
            - ./consumer-a/app:/source
    consumer-b:
        build:
            context: ./consumer-b/image-def
        volumes:
            - ./consumer-b/app:/source
