services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        image: mcr.microsoft.com/dotnet/sdk:6.0
        working_dir: /source
        command: [ "tail", "-f", "/dev/null" ]
        volumes:
            - ./producer/app:/source
    consumer-a:
        image: mcr.microsoft.com/dotnet/sdk:6.0
        working_dir: /source
        command: [ "tail", "-f", "/dev/null" ]
        volumes:
            - ./consumer-a/app:/source
    consumer-b:
        image: mcr.microsoft.com/dotnet/sdk:6.0
        working_dir: /source
        command: [ "tail", "-f", "/dev/null" ]
        volumes:
            - ./consumer-b/app:/source
