services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        build:
            context: ./producer/image-def
        init: true
        volumes:
            - ./producer/app:/source
    consumer:
        build:
            context: ./consumer/image-def
        init: true
        volumes:
            - ./consumer/app:/source
