x-dotnet-sdk: &dotnet-sdk
    image: mcr.microsoft.com/dotnet/sdk:6.0
    working_dir: /source
    init: true
    command: [ "tail", "-f", "/dev/null" ]

services:
    broker:
        image: rabbitmq:3.11-management
        ports:
            - "5672:5672"
            - "15672:15672"
    producer:
        << : *dotnet-sdk
        volumes:
            - ./producer/app:/source
    consumer:
        << : *dotnet-sdk
        volumes:
            - ./consumer/app:/source
